# Generated by Django 4.2.1 on 2023-05-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('studID', models.IntegerField()),
                ('birthDate', models.DateField()),
                ('gpa', models.FloatField()),
                ('phoneNumber', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=1)),
                ('status', models.CharField(max_length=1)),
                ('level', models.CharField(max_length=1)),
                ('department', models.CharField(max_length=2)),
            ],
        ),
    ]
