# Generated by Django 4.2.1 on 2023-05-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[{'CS', 'Computer Science'}, {'IS', 'Information Systems'}, {'IT', 'Information Technology'}, {'DS', 'Decision Support'}, {'General', 'Gen'}], max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[{'Male', 'M'}, {'Female', 'F'}], max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[{'act', 'Active'}, {'inact', 'InActive'}], max_length=25),
        ),
    ]
