# Generated by Django 4.2.1 on 2023-05-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_gender_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[{'Active', 'ACTIVE'}, {'IN-ACTIVE', 'INACTIVE'}], max_length=25),
        ),
    ]
